name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔧 Build Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - run: npm ci
      - run: npm run build

      - name: 📂 Sync Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          # Deploy compiled frontend
          local-dir: ./dist/ 
          # To public web root (adjust if in subfolder)
          server-dir: ./public_html/ 
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/src/**
            .env
            
      - name: 📂 Sync Backend API
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./public_html/api/
          server-dir: ./public_html/api/
